#ifndef __MQTT_PARAMS_H
#define __MQTT_PARAMS_H

#define MAX_QUEUE 50
#define MAX_GATEWAYS 5
#define MAX_MQTT_CLIENTID 21
#define MQTT_PAYLOAD_WIDTH 32
#define MQTT_PROTOCOL 0x01
#define MQTT_TOPIC_SAFE_BYTES 21
#define MQTT_TOPIC_MAX_BYTES 23
#define MQTT_MESSAGE_SAFE_BYTES 25
#define MQTT_MESSAGE_MAX_BYTES 27


#endif
